{{config(materialized='table')}}
 
with ads_basic_performance as (
    select CAST (ad_id AS STRING) as ad_id, 
    0 as add_to_cart,
    CAST (adset_id AS STRING) as adset_id,
    CAST (campaign_id AS STRING) as campaign_id,
    channel,
    clicks, 
    0 as comments,
    '0' as creative_id,
    DATE,
    0 as engagements,
    imps as impressions, 
    0 as installs,
    0 as likes,
    0 as link_clicks,
    '0' as placement_id,
    0 as post_click_conversion,
    0 as post_view_conversion,
    0 as posts,
    0 as purchase,
    0 as registrations,
    revenue,
    0 as shares, 
    spend, 
    conv as total_conversions, 
    0 as video_views from analytics-391020.dbt_impravado.src_ads_bing_all_data

    union all 

    select CAST (ad_id AS STRING), 
    add_to_cart,
    CAST (adset_id AS STRING),
    CAST (campaign_id AS STRING),
    channel,
    clicks, 
    comments,
    CAST (creative_id AS STRING),
    DATE,
    0 as engagements,
    impressions, 
    mobile_app_install,
    likes,
    inline_link_clicks as link_clicks,
    '0' as placement_id,
    0 as post_click_conversion,
    0 as post_view_conversion,
    0 as posts,
    purchase_value as purchase,
    0 as registrations,
    0 as revenue,
    shares, 
    spend, 
    0 as total_conversions, 
    views from analytics-391020.dbt_impravado.src_ads_creative_facebook_all_data

    union all 

    select CAST (ad_id AS STRING), 
    add_to_cart,
    '0',
    CAST (campaign_id AS STRING),
    channel,
    clicks, 
    0 as comments,
    '0' as creative_id,
    DATE,
    0 as engagements,
    impressions, 
    rt_installs+skan_app_install,
    0 as likes,
    0 as link_clicks,
    '0' as placement_id,
    0 as post_click_conversion,
    0 as post_view_conversion,
    0 as posts,
    purchase,
    registrations,
    0 as revenue,
    0 as shares, 
    spend, 
    conversions as total_conversions, 
    video_views  from analytics-391020.dbt_impravado.src_ads_tiktok_ads_all_data

    union all 

    select '0', 
    0 as add_to_cart,
    '0',
    CAST (campaign_id AS STRING),
    channel,
    clicks, 
    comments,
    '0' as creative_id,
    DATE,
    engagements,
    impressions, 
    0 as installs,
    likes,
    url_clicks as link_clicks,
    '0' as placement_id,
    0 as post_click_conversion,
    0 as post_view_conversion,
    0 as posts,
    0 as purchase,
    0 as registrations,
    0 as revenue,
    0 as shares, 
    spend, 
    0 as total_conversions, 
    video_total_views as video_views from analytics-391020.dbt_impravado.src_promoted_tweets_twitter_all_data
)

select * from ads_basic_performance
